version: "3.3"

networks:
  net:
    driver: bridge

services:

  m1:
    image: mongo:3.4
    container_name: m1
    command: mongod --replSet mwe --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  m2:
    image: mongo:3.4
    container_name: m2
    command: mongod --replSet mwe --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  m3:
    image: mongo:3.4
    container_name: m3
    command: mongod --replSet mwe --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  bootstrap:
    image: malkir/mongo-bootstrap:latest
    container_name: mongo-bootstrap
    ports:
    - 9090:9090
    command:
      - '-dataSet=mwe/m1:27017,m2:27017,m3:27017'
    networks:
      - net
