version: "3.3"

networks:
  net:

services:

  m1:
    image: mongo:3.4
    container_name: m1
    command: mongod --replSet mwe --smallfiles --port 27017
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == data1

  m2:
    image: mongo:3.4
    container_name: m2
    command: mongod --replSet mwe --smallfiles --port 27017
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == data1

  m3:
    image: mongo:3.4
    container_name: m3
    command: mongod --replSet mwe --smallfiles --port 27017
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == data1

  bootstrap:
    image: malkir/mongo-bootstrap:latest
    container_name: mongo-bootstrap
    ports:
    - 9090:9090
    command:
      - '-dataSet=mwe/m1:27017,m2:27017,m3:27017'
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.role == data1
